{% set name = "opentelemetry-sdk" %}
{% set version = "1.4.1" %}

# Common to all opentelemetry python libraries
{% set vsegments = version.split('.') %}
# not all packages in opentelemetry are at the most recent version
{% set preoffset = 19 %}
{% set canonical_minor_pre = (vsegments[1].split('b')[0] | int) - (preoffset | int) %}
{% set canonical_minor_rel = (vsegments[1] | int) %}
# determine the canonical minor version of the 1.x opentelemetry associated with this package
{% set canonical_minor = canonical_minor_rel if (vsegments[0] == '1') else canonical_minor_pre %}
{% set vpre = '0.{}b0'.format(canonical_minor + preoffset ) %}
{% set vrel = '1.{}'.format(canonical_minor) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef0d6fe69c0e6dffe24114af5dc87f8155347a59e8feba6da81cf96837623b6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - opentelemetry-api ==1.4.1
    - python >=3.4
    - opentelemetry-semantic-conventions ==0.23b2
    - opentelemetry-instrumentation ==0.23b2

test:
  imports:
    - opentelemetry.sdk
    - opentelemetry.sdk.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/measter/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
