{% set name = "opentelemetry-sdk" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf37830ca4f93d0910cf109749237c5cb4465e31a54dfad8400011e9822a2a14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ==1.12.0
    - python >=3.6
    - opentelemetry-semantic-conventions ==0.33b0
    - typing_extensions >=3.7.4
    # - setuptools >=16.0
    - dataclasses ==0.8
    # - setuptools >=16.0
    # - setuptools >=16.0
    # - setuptools >=16.0
    # - setuptools >=16.0
    # - setuptools >=16.0

test:
  imports:
    - opentelemetry.sdk
    - opentelemetry.sdk.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/measter/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
